# copied from .travis.yml
name: Run tests

on:
  push:
    branches:
      - master
    paths:
      - youtube_dl/**
      - test/**
  workflow_dispatch:
    inputs: {}

jobs:
  test:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.ytdl_test_set.may_fail || matrix.python.may_fail }}
    strategy:
      matrix:
        python: [
          { name: '2.7', may_fail: true, major: 2, jython: false, iron: false },
          { name: '3.8', may_fail: false, major: 3, jython: false, iron: false },
          { name: '3.7', may_fail: false, major: 3, jython: false, iron: false },
          { name: '3.6', may_fail: false, major: 3, jython: false, iron: false },
          { name: '3.5', may_fail: false, major: 3, jython: false, iron: false },
          { name: 'pypy3', may_fail: false, major: 3, jython: false, iron: false },
          { name: 'pypy2', may_fail: true, major: 2, jython: false, iron: false },
          { name: 'jython', may_fail: true, major: 2, jython: true, iron: false },
          { name: 'ironpython', may_fail: true, major: 2, jython: false, iron: true },
        ]
        ytdl_test_set: [
          { name: 'download', may_fail: true },
          { name: 'core', may_fail: false }
        ]
    env:
      YTDL_TEST_SET: ${{ matrix.ytdl_test_set.name }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python.name }}
        uses: actions/setup-python@v2
        if: ${{ !matrix.python.jython }}
        with:
          python-version: ${{ matrix.python.name }}
      - name: Install Jython
        if: ${{ matrix.python.jython }}
        run: |
          ./devscripts/install_jython.sh
          export PATH="$HOME/jython/bin:$PATH"
      - name: Install IronPython
        if: ${{ matrix.python.iron }}
        run: |
          git clone https://github.com/IronLanguages/ironpython2.git
          cd ironpython2/
          dotnet restore IronPython.sln --packages ./packages
          make
          echo -e "#!/bin/bash\nmono $PWD/bin/Release/net40/ipy.exe \"\$@\"" > /usr/bin/ironpy
          ironpy -m pip install nose
      - name: Install deps (Python 3)
        if: ${{ matrix.python.major == 3 && !(matrix.python.jython || matrix.python.iron) }}
        run: pip3 install nose
      - name: Install deps (Python 2)
        if: ${{ matrix.python.major == 2 && !(matrix.python.jython || matrix.python.iron) }}
        run: pip install nose
      - name: Run test
        continue-on-error: ${{ matrix.ytdl_test_set.may_fail || matrix.python.may_fail }}
        run: ./devscripts/run_tests.sh
  flake8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install deps
        run: pip3 install flake8
      - name: Run flake8 .
        run: flake8 .
